use clap::{Args, Subcommand};
use colored::Colorize;
use std::fs;
use std::path::Path;
use std::process::Command;
use crate::error::Result;

/// Zero-Knowledge proof operations using Noir circuits
#[derive(Args)]
pub struct ZkCommand {
    #[command(subcommand)]
    pub action: ZkAction,
}

#[derive(Subcommand)]
pub enum ZkAction {
    /// Initialize a new Noir ZK circuit project
    Init {
        /// Circuit template to use
        #[arg(value_parser = ["ownership", "merkle", "signature"])]
        circuit: String,
        
        /// Output directory
        #[arg(short, long, default_value = ".")]
        output: String,
    },
    
    /// Compile a Noir circuit
    Compile {
        /// Path to Noir project
        #[arg(default_value = ".")]
        path: String,
    },
    
    /// Generate a ZK proof
    Prove {
        /// Path to Prover.toml inputs
        #[arg(short, long, default_value = "Prover.toml")]
        inputs: String,
        
        /// Path to Noir project
        #[arg(default_value = ".")]
        path: String,
    },
    
    /// Verify a ZK proof
    Verify {
        /// Path to proof file
        #[arg(short, long)]
        proof: Option<String>,
        
        /// Path to Noir project
        #[arg(default_value = ".")]
        path: String,
    },
    
    /// Show installation instructions for Noir
    Setup,
}

impl ZkCommand {
    pub async fn run(&self) -> Result<()> {
        match &self.action {
            ZkAction::Init { circuit, output } => self.init_circuit(circuit, output),
            ZkAction::Compile { path } => self.compile_circuit(path),
            ZkAction::Prove { inputs, path } => self.generate_proof(inputs, path),
            ZkAction::Verify { proof, path } => self.verify_proof(proof.as_deref(), path),
            ZkAction::Setup => self.show_setup(),
        }
    }
    
    fn init_circuit(&self, circuit: &str, output: &str) -> Result<()> {
        println!("{} Noir ZK Circuit Generator", "→".bright_cyan());
        println!("{}", "─".repeat(50).bright_black());
        println!();
        
        let circuit_name = format!("{}-circuit", circuit);
        let base_path = Path::new(output).join(&circuit_name);
        
        if base_path.exists() {
            println!("{} Directory '{}' already exists!", "✗".bright_red(), circuit_name);
            return Ok(());
        }
        
        println!("  Creating Noir circuit: {}", circuit.bright_cyan());
        println!();
        
        // Create directories
        fs::create_dir_all(base_path.join("src"))?;
        
        // Generate Nargo.toml
        let nargo_toml = format!(r#"[package]
name = "{}"
type = "bin"
authors = [""]
compiler_version = ">=1.0.0"

[dependencies]
"#, circuit_name.replace("-", "_"));
        
        fs::write(base_path.join("Nargo.toml"), nargo_toml)?;
        println!("  ├─ Created Nargo.toml");
        
        // Generate circuit based on template
        let main_nr = match circuit {
            "ownership" => self.ownership_circuit(),
            "merkle" => self.merkle_circuit(),
            "signature" => self.signature_circuit(),
            _ => self.ownership_circuit(),
        };
        
        fs::write(base_path.join("src/main.nr"), main_nr)?;
        println!("  ├─ Created src/main.nr");
        
        // Generate Prover.toml
        let prover_toml = match circuit {
            "ownership" => r#"# Prover inputs
x = "5"
y = "10"
"#,
            "merkle" => r#"# Merkle proof inputs
leaf = "0x..."
path = ["0x...", "0x..."]
root = "0x..."
"#,
            "signature" => r#"# Signature verification inputs
message = "0x..."
signature = "0x..."
public_key = "0x..."
"#,
            _ => "# Prover inputs\n",
        };
        
        fs::write(base_path.join("Prover.toml"), prover_toml)?;
        println!("  ├─ Created Prover.toml");
        
        // Generate README
        let readme = format!(r#"# {} Circuit

Noir ZK circuit generated by SolPrivacy CLI.

## Prerequisites

```bash
# Install Noir
curl -L https://raw.githubusercontent.com/noir-lang/noirup/main/install | bash
noirup -v 1.0.0-beta.13
```

## Usage

```bash
# Check circuit
nargo check

# Generate proof
nargo prove

# Verify proof
nargo verify
```

## Deploy to Solana

```bash
# Install Sunspot (requires Go 1.24+)
git clone https://github.com/reilabs/sunspot.git
cd sunspot/go && go build -o sunspot .

# Generate Solana verifier
sunspot verifier-gen
```

## Resources

- [Noir Documentation](https://noir-lang.org/docs)
- [Solana Noir Examples](https://github.com/solana-foundation/noir-examples)
"#, circuit_name);
        
        fs::write(base_path.join("README.md"), readme)?;
        println!("  └─ Created README.md");
        
        println!();
        println!("{} Circuit created at: {}", "✓".bright_green(), base_path.display());
        println!();
        println!("  {}:", "Next Steps".bright_white());
        println!("    1. cd {}", circuit_name);
        println!("    2. nargo check");
        println!("    3. Edit Prover.toml with your inputs");
        println!("    4. nargo prove");
        
        Ok(())
    }
    
    fn ownership_circuit(&self) -> String {
        r#"// Ownership Proof Circuit
// Proves knowledge of values without revealing them

fn main(x: Field, y: Field) {
    // Prove that x is not equal to y
    assert(x != y);
    
    // Prove knowledge of x and y where their sum equals a public value
    let sum = x + y;
    
    // Additional constraint: product must be positive
    let product = x * y;
    assert(product != 0);
}

// Test function
#[test]
fn test_ownership() {
    main(5, 10);
}
"#.to_string()
    }
    
    fn merkle_circuit(&self) -> String {
        r#"// Sparse Merkle Tree Exclusion Proof
// Proves a value is NOT in a Merkle tree (e.g., not on a blacklist)

use std::hash::poseidon2::Poseidon2;

fn main(
    leaf: Field,
    path: [Field; 32],
    indices: [u1; 32],
    root: pub Field
) {
    // Verify the Merkle proof
    let mut current = leaf;
    
    for i in 0..32 {
        let sibling = path[i];
        
        if indices[i] == 0 {
            // Current is left child
            current = Poseidon2::hash([current, sibling], 2);
        } else {
            // Current is right child
            current = Poseidon2::hash([sibling, current], 2);
        }
    }
    
    // Verify computed root matches expected root
    assert(current == root);
}
"#.to_string()
    }
    
    fn signature_circuit(&self) -> String {
        r#"// ECDSA Signature Verification Circuit
// Proves valid signature without revealing private key

use std::ecdsa_secp256k1::verify_signature;

fn main(
    message_hash: [u8; 32],
    signature: [u8; 64],
    public_key_x: [u8; 32],
    public_key_y: [u8; 32]
) {
    // Verify the ECDSA signature
    let valid = verify_signature(
        public_key_x,
        public_key_y,
        signature,
        message_hash
    );
    
    assert(valid);
}
"#.to_string()
    }
    
    fn compile_circuit(&self, path: &str) -> Result<()> {
        println!("{} Compiling Noir Circuit", "→".bright_cyan());
        println!("{}", "─".repeat(50).bright_black());
        println!();
        
        // Check if nargo is installed
        let nargo_check = Command::new("nargo")
            .arg("--version")
            .output();
        
        match nargo_check {
            Ok(output) => {
                if output.status.success() {
                    let version = String::from_utf8_lossy(&output.stdout);
                    println!("  Nargo: {}", version.trim().bright_green());
                } else {
                    println!("{} Nargo not found!", "✗".bright_red());
                    println!();
                    self.show_setup()?;
                    return Ok(());
                }
            }
            Err(_) => {
                println!("{} Nargo not installed!", "✗".bright_red());
                println!();
                self.show_setup()?;
                return Ok(());
            }
        }
        
        println!("  Path: {}", path);
        println!();
        
        // Run nargo compile
        println!("{} Running 'nargo compile'...", "→".bright_cyan());
        
        let result = Command::new("nargo")
            .arg("compile")
            .current_dir(path)
            .output();
        
        match result {
            Ok(output) => {
                if output.status.success() {
                    println!("{} Compilation successful!", "✓".bright_green());
                    println!();
                    let stdout = String::from_utf8_lossy(&output.stdout);
                    if !stdout.is_empty() {
                        println!("{}", stdout);
                    }
                } else {
                    println!("{} Compilation failed", "✗".bright_red());
                    let stderr = String::from_utf8_lossy(&output.stderr);
                    if !stderr.is_empty() {
                        println!("{}", stderr);
                    }
                }
            }
            Err(e) => {
                println!("{} Failed to run nargo: {}", "✗".bright_red(), e);
            }
        }
        
        Ok(())
    }
    
    fn generate_proof(&self, inputs: &str, path: &str) -> Result<()> {
        println!("{} Generating ZK Proof", "→".bright_cyan());
        println!("{}", "─".repeat(50).bright_black());
        println!();
        
        println!("  Inputs: {}", inputs);
        println!("  Path: {}", path);
        println!();
        
        // Check for Prover.toml
        let prover_path = Path::new(path).join(inputs);
        if !prover_path.exists() {
            println!("{} {} not found", "✗".bright_red(), inputs);
            println!("  Create a Prover.toml with your private inputs");
            return Ok(());
        }
        
        println!("{} Running 'nargo prove'...", "→".bright_cyan());
        
        let result = Command::new("nargo")
            .arg("prove")
            .current_dir(path)
            .output();
        
        match result {
            Ok(output) => {
                if output.status.success() {
                    println!("{} Proof generated!", "✓".bright_green());
                    println!();
                    println!("  Output: proofs/<circuit_name>.proof");
                    println!();
                    println!("  {}:", "Verify with".bright_white());
                    println!("    solprivacy zk verify");
                } else {
                    println!("{} Proof generation failed", "✗".bright_red());
                    let stderr = String::from_utf8_lossy(&output.stderr);
                    if !stderr.is_empty() {
                        println!("{}", stderr);
                    }
                }
            }
            Err(e) => {
                println!("{} Failed to run nargo: {}", "✗".bright_red(), e);
                self.show_setup()?;
            }
        }
        
        Ok(())
    }
    
    fn verify_proof(&self, _proof: Option<&str>, path: &str) -> Result<()> {
        println!("{} Verifying ZK Proof", "→".bright_cyan());
        println!("{}", "─".repeat(50).bright_black());
        println!();
        
        println!("{} Running 'nargo verify'...", "→".bright_cyan());
        
        let result = Command::new("nargo")
            .arg("verify")
            .current_dir(path)
            .output();
        
        match result {
            Ok(output) => {
                if output.status.success() {
                    println!("{} Proof is valid!", "✓".bright_green());
                    println!();
                    println!("  The prover knows inputs satisfying the circuit constraints");
                    println!("  without revealing those inputs.");
                    println!();
                    println!("  {}:", "Deploy to Solana".bright_white());
                    println!("    1. Install Sunspot: https://github.com/reilabs/sunspot");
                    println!("    2. sunspot verifier-gen");
                    println!("    3. Deploy verifier program to Solana");
                } else {
                    println!("{} Proof verification failed", "✗".bright_red());
                    let stderr = String::from_utf8_lossy(&output.stderr);
                    if !stderr.is_empty() {
                        println!("{}", stderr);
                    }
                }
            }
            Err(e) => {
                println!("{} Failed to run nargo: {}", "✗".bright_red(), e);
                self.show_setup()?;
            }
        }
        
        Ok(())
    }
    
    fn show_setup(&self) -> Result<()> {
        println!("{} Noir ZK Development Setup", "→".bright_cyan());
        println!("{}", "─".repeat(50).bright_black());
        println!();
        
        println!("  {}:", "Step 1: Install Noir".bright_white());
        println!("    curl -L https://raw.githubusercontent.com/noir-lang/noirup/main/install | bash");
        println!("    noirup -v 1.0.0-beta.13");
        println!();
        
        println!("  {}:", "Step 2: Verify Installation".bright_white());
        println!("    nargo --version");
        println!();
        
        println!("  {}:", "Step 3 (Optional): Install Sunspot for Solana".bright_white());
        println!("    # Requires Go 1.24+");
        println!("    git clone https://github.com/reilabs/sunspot.git");
        println!("    cd sunspot/go && go build -o sunspot .");
        println!("    export PATH=\"$HOME/sunspot/go:$PATH\"");
        println!();
        
        println!("  {}:", "Resources".bright_white());
        println!("    Noir Docs: https://noir-lang.org/docs");
        println!("    Solana Examples: https://github.com/solana-foundation/noir-examples");
        println!("    Aztec (Noir): https://aztec.network");
        println!();
        
        println!("  {}:", "Hackathon Track".bright_white());
        println!("    Noir ZK Applications: $10,000 prize");
        
        Ok(())
    }
}
